//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RabbitMQTest.Web.WCFMQService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFMQService.IMQService")]
    public interface IMQService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMQService/ContactListApply", ReplyAction="http://tempuri.org/IMQService/ContactListApplyResponse")]
        RabbitMQTest.Model.ResponseEntity ContactListApply(RabbitMQTest.Model.RequestEntity request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMQService/ContactListApply", ReplyAction="http://tempuri.org/IMQService/ContactListApplyResponse")]
        System.Threading.Tasks.Task<RabbitMQTest.Model.ResponseEntity> ContactListApplyAsync(RabbitMQTest.Model.RequestEntity request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMQServiceChannel : RabbitMQTest.Web.WCFMQService.IMQService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MQServiceClient : System.ServiceModel.ClientBase<RabbitMQTest.Web.WCFMQService.IMQService>, RabbitMQTest.Web.WCFMQService.IMQService {
        
        public MQServiceClient() {
        }
        
        public MQServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MQServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MQServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MQServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RabbitMQTest.Model.ResponseEntity ContactListApply(RabbitMQTest.Model.RequestEntity request) {
            return base.Channel.ContactListApply(request);
        }
        
        public System.Threading.Tasks.Task<RabbitMQTest.Model.ResponseEntity> ContactListApplyAsync(RabbitMQTest.Model.RequestEntity request) {
            return base.Channel.ContactListApplyAsync(request);
        }
    }
}
